// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUeECKfwLag9aHu07db7WVj76-wvw3hqE',
    appId: '1:965901070966:web:1f7cadefe0585309992557',
    messagingSenderId: '965901070966',
    projectId: 'myproject-54746',
    authDomain: 'myproject-54746.firebaseapp.com',
    storageBucket: 'myproject-54746.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEI83TPd-22g26DVqt90wc4MK_2HfU-0w',
    appId: '1:965901070966:android:9786a98c88e38a53992557',
    messagingSenderId: '965901070966',
    projectId: 'myproject-54746',
    storageBucket: 'myproject-54746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxAs39yrkEq0qfNap-ASmPccXtypCOG08',
    appId: '1:965901070966:ios:b509c01b3ae4df65992557',
    messagingSenderId: '965901070966',
    projectId: 'myproject-54746',
    storageBucket: 'myproject-54746.appspot.com',
    iosBundleId: 'com.example.geoFencing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxAs39yrkEq0qfNap-ASmPccXtypCOG08',
    appId: '1:965901070966:ios:b509c01b3ae4df65992557',
    messagingSenderId: '965901070966',
    projectId: 'myproject-54746',
    storageBucket: 'myproject-54746.appspot.com',
    iosBundleId: 'com.example.geoFencing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUeECKfwLag9aHu07db7WVj76-wvw3hqE',
    appId: '1:965901070966:web:bf80f96739a388e2992557',
    messagingSenderId: '965901070966',
    projectId: 'myproject-54746',
    authDomain: 'myproject-54746.firebaseapp.com',
    storageBucket: 'myproject-54746.appspot.com',
  );
}
